name: Update Docker Hub Description

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - '.github/workflows/docker-description.yml'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-description:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nseba/commit-ai
          readme-filepath: ./README.md
          short-description: "AI-powered commit message generator for Git repositories using multiple LLM providers"
          enable-url-completion: true
